### ISSUE TITLE
Request for offline datasets

### ISSUE THREAD

**Issue by linhlpv** [BattleWen/IGDF#1]
Hi @BattleWen, @Kavka1,

Thank you for your amazing work . I am very interested in exploring and potentially extending your research. To facilitate this, I would like to request access to the datasets that you used to train your models.

Thank you.
Best,
Linh

**Comment by BattleWen** [comment]
Hi @linhlpv ,

Thank you very much for your interest in our work. You can find the offline dataset at the following Google Drive link (https://drive.google.com/file/d/1rW3y75GlUY5K0hax3qdYk7MYnmd9_eSL/view?usp=drive_link). It is important to note that for the "broken thighs" and "morphology shift" tasks, we are only providing a 1M replay transitions as the source dataset. If you would like to collect additional datasets, you can use the `algorithms/collect.py` file provided in the latest version. If you have any other questions, we can discuss them further.

Best，
Xiaoyu Wen

**Comment by linhlpv** [comment]
Hi @BattleWen ,

Thank you for your reply.

I just have one more small question. What is the time step that you use to pick the policy for collecting medium and medium-expert dataset? As I see in the collect.py, you train the SAC 1M steps and collect all the data in the replay buffer and store them. Is it the version for medium-replay dataset?

Thank you again and have a nice day.
Best,
Linh

**Comment by BattleWen** [comment]
Not exactly. You can refer to OpenAI's Gym (https://github.com/Farama-Foundation/d4rl/wiki/Tasks) for the definition of the Medium-Replay dataset. 

`Medium-Replay uses the replay buffer of a policy trained up to the performance of the medium agent (approximately 1/3 the performance of the expert). Timeouts in this dataset are not always marked when the agent reaches the max trajectory length, but rather when 1000 timesteps have been sampled for a particular training iteration.` 

So the number of transitions might not be exactly 1M. In our paper, to keep the source dataset consistent with other environments, we simplified it by uniformly collecting 1M transitions.

**Comment by BattleWen** [comment]
But for body mass and joint noise tasks, we strictly collected different tasks according to their definitions, such as Medium, Medium-Replay and Medium-expert.

**Comment by linhlpv** [comment]
I see. So to create medium dataset, for each tasks, do we need to manually pick the checkpoint that reaches approximately 1/3 expert performance or do you just fix by uniformly picking the checkpoints at 1/3 max iteration?

**Comment by BattleWen** [comment]
The former. For the medium dataset, we use checkpoints that achieve approximately 1/3 of the expert performance to rollout data.

**Comment by linhlpv** [comment]
Cool. And you train it with 1M iterations as the expert performance, don't you?

**Comment by BattleWen** [comment]
OpenAI has not specified the exact number of iterations corresponding to expert performance. You can consider the performance of SAC after training has stabilized as the expert performance.

**Comment by linhlpv** [comment]
Ok, I got it. Thank u so much.
